### ISSUE TITLE
Can this theme be updated to support Gnome 3.20+?

### ISSUE THREAD

**Issue by Austaras** [kevin-leptons/venom#1]
lots of elements break in Gnome 3.24

**Comment by kevin-leptons** [comment]
Ha ha, because it supports only GNOME 3.14. 

I also want it run on multi GNOME versions. Unfortunately, that mean lot of work to do such as read specifications, write code, modify builder, test. Try to imagine that it supports GNOME v3.14, v3.16, v3.20 and your GNOME v3.24, and here are works to do.

- read specification GNOME v3.14,  write code, write builder, test, and loop until it's expected
- read specification GNOME v3.16,  write code, write builder, test, and loop until it's expected
- read specification GNOME v3.20,  write code, write builder, test, and loop until it's expected
- read specification GNOME v3.24,  write code, write builder, test, and loop until it's expected

It's terrible and I haven't other solutions. So now, multi version is impossible with only me.

However, if you can fork **venom** to new repository, specific GNOME version, develop until it look same as **venom** then I am happy to merge it.
